### ISSUE TITLE
Add server show command

### ISSUE THREAD

**Issue by briangustafson** [oracle/knife-bmcs#19]
Proposed interface and output is below. A few notes:
- The output is taken directly from server create, see https://github.com/oracle/knife-bmcs/blob/master/lib/chef/knife/bmcs_server_create.rb#L160. We should probably share the code.
- The method of getting IP address in server create is simpler than the logic needed in the general case, since on server create we know that the instance can only have 1 VNIC and that that VNIC is in the same compartment.
- We can certainly improve on the output below in the future (for one, it would be nice to show the name of the compartment and the image in addition to the ID), but the output below should be a reasonable starting point. (It's also useful to look at what the console is showing for an instance.)
- "server show" is the standard terminology used in other knife plugins, as opposed to server get or info.

knife bmcs server show --instance-id <Instance OCID>

Display Name: knife_integ_instance
Instance ID: ocid1.instance.oc1.iad.abuwcljs2qts5jvuthfscqvev77wtiwhnu37znyuhwy4hxzx65gxefzw3ppq
Availability Domain: IwGV:US-ASHBURN-AD-2
Compartment ID: ocid1.compartment.oc1..aaaaaaaa6y3zzwkqlcyupl6msnblrhffavz6bu6phk7q265kfsil3ilekksq
Region: iad
Image ID: ocid1.image.oc1.iad.aaaaaaaah2d5y4jlyi6q5mus4ihabunzdzuiwmuc3pequv27jfkc5eb4ylcq
Shape: VM.Standard1.2
Public IP Address: 129.213.46.57
Private IP Address: 10.0.1.5
Hostname: myintegtesthostname
Node Name: knife_integ_instance

**Comment by lidl** [comment]
The code that displays the hostname, private ip address and public ip address is currently geared towards displaying those parameters from the first/primary vnic for a server instance.  How do you want the information displayed for additional vnic interfaces?

**Comment by briangustafson** [comment]
Resolved by @lidl with https://github.com/oracle/knife-bmcs/pull/26.
