### ISSUE TITLE
Add optional launch instance params to server create

### ISSUE THREAD

**Issue by briangustafson** [oracle/knife-bmcs#5]
There are a few recently-added parameters for launch instance that are not yet available in "knife bmcs server create".  See the latest launch instance options at https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/requests/LaunchInstanceDetails. At least a subset of additional options should be exposed in the same way as in the CLI. The most relevant options to add are (as copied from the CLI help for "bmcs compute instance launch -?"): 

  --assign-public-ip BOOLEAN      Whether the default VNIC attached to this
                                  instance should be assigned a public IP
                                  address. Defaults to whether the subnet is
                                  public or private. If not set and the VNIC
                                  is being created in a private subnet (i.e.,
                                  where prohibitPublicIpOnVnic=true in the
                                  Subnet), then no public IP address is
                                  assigned. If not set and the subnet is
                                  public (prohibitPublicIpOnVnic=false), then
                                  a public IP address is assigned. If set to
                                  true and prohibitPublicIpOnVnic=true, an
                                  error is returned.
  --private-ip TEXT               A private IP address of your choice to
                                  assign to the default VNIC attached to this
                                  instance. Must be an available IP address
                                  within the subnet's CIDR. If no value is
                                  specified, a private IP address from the
                                  subnet will be automatically assigned.

**Comment by jcobol** [comment]
New options are listed under https://docs.us-phoenix-1.oraclecloud.com/api/#/en/iaas/20160918/requests/CreateVnicDetails.  VNIC details are passed to launch_instance.

**Comment by briangustafson** [comment]
Fixed by @jcobol with https://github.com/oracle/knife-bmcs/pull/18.
